project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - research.qmd
    - publications.qmd
    - projects.qmd
    - teaching.qmd
    - cv.qmd
    - achievements.qmd
    - contact.qmd

website:
  title: "Mojtaba A. Farahani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: achievements.qmd
        text: Achievements
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
