project:
  type: website
  output-dir: docs

website:
  title: "Mojtaba (Moji) Farahani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: achievements.qmd
        text: Achievements
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true